[profile.default]
src = "."
out = "out"
libs = ["lib"]
test = "test"
cache = true
cache_path = "cache"

solc = "0.8.31"
optimizer = true
optimizer_runs = 200

# Gas reporting
gas_reports = ["LamportLib", "LamportVerifier", "LamportModule"]

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[profile.ci]
fuzz = { runs = 10000 }

[profile.intense]
fuzz = { runs = 100000 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
